const data = [
	{
		_id: "665671158f4a1b2c3d4e5f6a",
		name: "Причіп легковий Кремень ПЛ-2",
		slug: "prychip-lehkovyy-kremen-pl-2",
		description:
			"<p>Надійний легковий причіп для транспортування різноманітних вантажів. Оснащений ресорною підвіскою та посиленою рамою.</p>",
		shortDescription: "Легковий причіп з ресорною підвіскою.",
		brand: "Кремень",
		model: "ПЛ-2",
		category: "Легкові причепи",
		price: 35000,
		currency: "UAH",
		inStock: true,
		quantity: 5,
		images: [
			"https://yourstore.com/images/kremen-pl2-main.jpg",
			"https://yourstore.com/images/kremen-pl2-side.jpg",
			"https://yourstore.com/images/kremen-pl2-interior.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "750",
				unit: "кг",
			},
			{
				name: "Довжина кузова",
				value: "2000",
				unit: "мм",
			},
			{
				name: "Ширина кузова",
				value: "1200",
				unit: "мм",
			},
			{
				name: "Висота борту",
				value: "400",
				unit: "мм",
			},
			{
				name: "Тип підвіски",
				value: "Ресорна",
			},
			{
				name: "Колісна формула",
				value: "1R",
			},
		],
		metaTitle: "Купити легковий причіп Кремень ПЛ-2 в Україні",
		metaDescription:
			"Детальний опис та характеристики причепа Кремень ПЛ-2. Доставка по Україні.",
		keywords: ["причіп", "легковий причіп", "Кремень", "ПЛ-2", "купити причіп"],
		isFeatured: true,
		createdAt: "2024-05-29T20:00:00.000Z",
		updatedAt: "2024-05-29T21:00:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f6b",
		name: "Причіп для човна ЛАВ-8101",
		slug: "prychip-dlya-chovna-lav-8101",
		description:
			"<p>Спеціалізований причіп для перевезення човнів довжиною до 4.5 м. Оснащений лебідкою та регульованими ложементами.</p>",
		shortDescription: "Причіп для човна до 4.5 м.",
		brand: "ЛАВ",
		model: "8101",
		category: "Причепи для човнів",
		price: 42000,
		currency: "UAH",
		inStock: true,
		quantity: 3,
		images: [
			"https://yourstore.com/images/lav-8101-main.jpg",
			"https://yourstore.com/images/lav-8101-side.jpg",
		],
		specifications: [
			{
				name: "Довжина човна",
				value: "4.5",
				unit: "м",
			},
			{
				name: "Вантажопідйомність",
				value: "500",
				unit: "кг",
			},
			{
				name: "Тип підвіски",
				value: "Ресорна",
			},
			{
				name: "Наявність лебідки",
				value: "Так",
			},
		],
		metaTitle: "Купити причіп для човна ЛАВ-8101",
		metaDescription:
			"Причіп для човна ЛАВ-8101 - надійне рішення для транспортування плавзасобів.",
		keywords: ["причіп для човна", "ЛАВ", "8101", "човен"],
		isFeatured: false,
		createdAt: "2024-05-29T20:05:00.000Z",
		updatedAt: "2024-05-29T21:05:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f6c",
		name: "Торговий причіп МАЗ-ТП10",
		slug: "torgovyy-prychip-maz-tp10",
		description:
			"<p>Універсальний торговий причіп для виїзної торгівлі. Внутрішнє обладнання замовника. Може бути використаний для кави, фаст-фуду.</p>",
		shortDescription: "Причіп для виїзної торгівлі.",
		brand: "МАЗ",
		model: "ТП10",
		category: "Торгові причепи",
		price: 95000,
		currency: "UAH",
		inStock: true,
		quantity: 1,
		images: [
			"https://yourstore.com/images/maz-tp10-main.jpg",
			"https://yourstore.com/images/maz-tp10-open.jpg",
		],
		specifications: [
			{
				name: "Довжина кузова",
				value: "3000",
				unit: "мм",
			},
			{
				name: "Ширина кузова",
				value: "2000",
				unit: "мм",
			},
			{
				name: "Висота внутрішня",
				value: "2200",
				unit: "мм",
			},
			{
				name: "Тип підвіски",
				value: "Торсіонна",
			},
		],
		metaTitle: "Купити торговий причіп МАЗ-ТП10",
		metaDescription: "Мобільний торговий причіп МАЗ-ТП10 для кави, фаст-фуду.",
		keywords: ["торговий причіп", "МАЗ", "ТП10", "фаст-фуд"],
		isFeatured: true,
		createdAt: "2024-05-29T20:10:00.000Z",
		updatedAt: "2024-05-29T21:10:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f6d",
		name: "Причіп для квадроцикла АРМ-1500",
		slug: "prychip-dlya-kvadrotsykla-arm-1500",
		description:
			"<p>Міцний причіп для транспортування одного квадроцикла. Обладнаний трапом для заїзду.</p>",
		shortDescription: "Причіп для квадроцикла.",
		brand: "АРМ",
		model: "1500",
		category: "Причепи для квадроциклів",
		price: 28000,
		currency: "UAH",
		inStock: true,
		quantity: 2,
		images: [
			"https://yourstore.com/images/arm-1500-main.jpg",
			"https://yourstore.com/images/arm-1500-with-quad.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "750",
				unit: "кг",
			},
			{
				name: "Довжина платформи",
				value: "2500",
				unit: "мм",
			},
			{
				name: "Ширина платформи",
				value: "1300",
				unit: "мм",
			},
			{
				name: "Наявність трапа",
				value: "Так",
			},
		],
		metaTitle: "Купити причіп для квадроцикла АРМ-1500",
		metaDescription:
			"Надійний причіп для транспортування квадроциклів АРМ-1500.",
		keywords: ["причіп для квадроцикла", "АРМ", "1500", "квадроцикл"],
		isFeatured: false,
		createdAt: "2024-05-29T20:15:00.000Z",
		updatedAt: "2024-05-29T21:15:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f6e",
		name: "Причіп самоскидний Корида-С5",
		slug: "prychip-samoskydnyy-koryda-s5",
		description:
			"<p>Універсальний самоскидний причіп для перевезення сипучих матеріалів. Ручний механізм перекидання кузова.</p>",
		shortDescription: "Самоскидний причіп.",
		brand: "Корида",
		model: "С5",
		category: "Легкові причепи",
		price: 48000,
		currency: "UAH",
		inStock: false,
		quantity: 0,
		images: [
			"https://yourstore.com/images/koryda-s5-main.jpg",
			"https://yourstore.com/images/koryda-s5-dump.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "750",
				unit: "кг",
			},
			{
				name: "Об'єм кузова",
				value: "1.5",
				unit: "м³",
			},
			{
				name: "Механізм перекидання",
				value: "Ручний",
			},
		],
		metaTitle: "Причіп самоскидний Корида-С5",
		metaDescription:
			"Купити самоскидний причіп Корида-С5 для сипучих матеріалів.",
		keywords: ["причіп самоскидний", "Корида", "С5", "сипучі матеріали"],
		isFeatured: false,
		createdAt: "2024-05-29T20:20:00.000Z",
		updatedAt: "2024-05-29T21:20:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f6f",
		name: "Причіп для мотоблока Агро-250",
		slug: "prychip-dlya-motobloka-agro-250",
		description:
			"<p>Компактний причіп для використання з мотоблоком. Ідеально підходить для перевезення невеликих вантажів на городі.</p>",
		shortDescription: "Причіп для мотоблока.",
		brand: "Агро",
		model: "250",
		category: "Спеціалізовані причепи",
		price: 12000,
		currency: "UAH",
		inStock: true,
		quantity: 8,
		images: [
			"https://yourstore.com/images/agro-250-main.jpg",
			"https://yourstore.com/images/agro-250-attached.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "250",
				unit: "кг",
			},
			{
				name: "Розмір кузова",
				value: "1200x800",
				unit: "мм",
			},
			{
				name: "Тип зчеплення",
				value: "Мотоблочне",
			},
		],
		metaTitle: "Купити причіп для мотоблока Агро-250",
		metaDescription: "Малогабаритний причіп Агро-250 для мотоблока.",
		keywords: ["причіп для мотоблока", "Агро", "250", "мотоблок"],
		isFeatured: false,
		createdAt: "2024-05-29T20:25:00.000Z",
		updatedAt: "2024-05-29T21:25:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f70",
		name: "Причіп платформа Евакуатор-3500",
		slug: "prychip-platforma-evakuator-3500",
		description:
			"<p>Двовісний причіп-платформа для перевезення автомобілів або іншої техніки. Посилена рама та гальмівна система.</p>",
		shortDescription: "Причіп-евакуатор для авто.",
		brand: "Евакуатор",
		model: "3500",
		category: "Причепи для транспортування техніки",
		price: 110000,
		currency: "UAH",
		inStock: true,
		quantity: 1,
		images: [
			"https://yourstore.com/images/evacuator-3500-main.jpg",
			"https://yourstore.com/images/evacuator-3500-with-car.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "2700",
				unit: "кг",
			},
			{
				name: "Кількість осей",
				value: "2",
			},
			{
				name: "Гальмівна система",
				value: "Інерційна",
			},
			{
				name: "Довжина платформи",
				value: "4000",
				unit: "мм",
			},
		],
		metaTitle: "Купити причіп-платформу Евакуатор-3500",
		metaDescription: "Надійний причіп для перевезення автомобілів.",
		keywords: ["причіп платформа", "евакуатор", "перевезення авто"],
		isFeatured: true,
		createdAt: "2024-05-29T20:30:00.000Z",
		updatedAt: "2024-05-29T21:30:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f71",
		name: "Причіп-дача 'Караван' М-2000",
		slug: "prychip-dacha-karavan-m-2000",
		description:
			"<p>Комфортний причіп-дача для подорожей. Обладнаний спальним місцем, міні-кухнею та шафами.</p>",
		shortDescription: "Причіп для кемпінгу.",
		brand: "Караван",
		model: "М-2000",
		category: "Причепи-дачі",
		price: 180000,
		currency: "UAH",
		inStock: false,
		quantity: 0,
		images: [
			"https://yourstore.com/images/karavan-m2000-main.jpg",
			"https://yourstore.com/images/karavan-m2000-interior.jpg",
		],
		specifications: [
			{
				name: "Спальних місць",
				value: "2",
			},
			{
				name: "Наявність кухні",
				value: "Так",
			},
			{
				name: "Довжина",
				value: "3500",
				unit: "мм",
			},
		],
		metaTitle: "Купити причіп-дачу Караван М-2000",
		metaDescription: "Комфортний причіп для подорожей Караван М-2000.",
		keywords: ["причіп-дача", "кемпінг", "Караван", "подорожі"],
		isFeatured: false,
		createdAt: "2024-05-29T20:35:00.000Z",
		updatedAt: "2024-05-29T21:35:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f72",
		name: "Причіп для мотоцикла Експрес-1",
		slug: "prychip-dlya-mototsykla-ekspres-1",
		description:
			"<p>Легкий та маневрений причіп для перевезення одного мотоцикла або скутера.</p>",
		shortDescription: "Причіп для мотоцикла.",
		brand: "Експрес",
		model: "1",
		category: "Причепи для мотоциклів",
		price: 25000,
		currency: "UAH",
		inStock: true,
		quantity: 4,
		images: [
			"https://yourstore.com/images/express-1-main.jpg",
			"https://yourstore.com/images/express-1-with-moto.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "300",
				unit: "кг",
			},
			{
				name: "Довжина платформи",
				value: "2200",
				unit: "мм",
			},
			{
				name: "Тип кріплення",
				value: "Колісні зажими",
			},
		],
		metaTitle: "Купити причіп для мотоцикла Експрес-1",
		metaDescription:
			"Надійний причіп Експрес-1 для транспортування мотоциклів.",
		keywords: ["причіп для мотоцикла", "Експрес", "мотоцикл"],
		isFeatured: false,
		createdAt: "2024-05-29T20:40:00.000Z",
		updatedAt: "2024-05-29T21:40:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f73",
		name: "Причіп багажний Дельфін-750",
		slug: "prychip-bagazhnyy-delfin-750",
		description:
			"<p>Невеликий, але місткий причіп для перевезення багажу та дрібних вантажів. Ідеальний для дому та дачі.</p>",
		shortDescription: "Компактний багажний причіп.",
		brand: "Дельфін",
		model: "750",
		category: "Легкові причепи",
		price: 22000,
		currency: "UAH",
		inStock: true,
		quantity: 7,
		images: [
			"https://yourstore.com/images/delfin-750-main.jpg",
			"https://yourstore.com/images/delfin-750-loaded.jpg",
		],
		specifications: [
			{
				name: "Вантажопідйомність",
				value: "500",
				unit: "кг",
			},
			{
				name: "Об'єм кузова",
				value: "1.0",
				unit: "м³",
			},
			{
				name: "Наявність тенту",
				value: "Опціонально",
			},
		],
		metaTitle: "Купити багажний причіп Дельфін-750",
		metaDescription:
			"Малогабаритний причіп Дельфін-750 для багажу та дрібних вантажів.",
		keywords: ["причіп багажний", "Дельфін", "750", "багаж"],
		isFeatured: false,
		createdAt: "2024-05-29T20:45:00.000Z",
		updatedAt: "2024-05-29T21:45:00.000Z",
	},
	{
		_id: "665671158f4a1b2c3d4e5f74",
		name: "Причіп для перевезення тварин Звіровоз-М",
		slug: "prychip-dlya-perevezennya-tvaryn-zvirovoz-m",
		description:
			"<p>Спеціалізований причіп для безпечного транспортування дрібних та середніх тварин. Вентиляція та легке очищення.</p>",
		shortDescription: "Причіп для тварин.",
		brand: "Звіровоз",
		model: "М",
		category: "Спеціалізовані причепи",
		price: 60000,
		currency: "UAH",
		inStock: true,
		quantity: 2,
		images: [
			"https://yourstore.com/images/zvirovoz-m-main.jpg",
			"https://yourstore.com/images/zvirovoz-m-interior.jpg",
		],
		specifications: [
			{
				name: "Макс. кількість тварин",
				value: "2",
			},
			{
				name: "Система вентиляції",
				value: "Природна",
			},
			{
				name: "Розміри внутрішні",
				value: "1800x1000x1200",
				unit: "мм",
			},
		],
		metaTitle: "Купити причіп для тварин Звіровоз-М",
		metaDescription:
			"Надійний причіп Звіровоз-М для безпечного перевезення тварин.",
		keywords: ["причіп для тварин", "Звіровоз", "перевезення тварин"],
		isFeatured: false,
		createdAt: "2024-05-29T20:50:00.000Z",
		updatedAt: "2024-05-29T21:50:00.000Z",
	},
];

export default data;
